name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}

      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ github.repository }}:1.0.${{ github.run_id }}
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:1.0.${{ github.run_id }}
            ghcr.io/${{ github.repository }}:latest
